---
- name: Update repository cache
  apt:
    update_cache: yes

- name: Download apt repo keys
  get_url:
    url: "https://www.virtualbox.org/download/{{ item }}.asc"
    dest: "/home/vagrant/{{ item }}"
    mode: 0644
  loop:
    "{{ devlaps_vagrant.deb_apt_repo_keys }}"

- name: Install repo keys.
  apt_key:
    data: "{{ lookup('file', 'oracle_vbox_2016.asc') }}"
    state: present

- name: Install repo key.
  apt_key:
    data: "{{ lookup('file', 'oracle_vbox.asc') }}"
    state: present

- name: Add virtualbox apt repo.
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian bionic contrib
    state: present

- name: Clean up asc files
  file:
    path: "/home/vagrant/{{ item }}"
    state: absent
  loop:
    "{{ devlaps_vagrant.deb_apt_repo_keys }}"

- name: Install virtualbox and vagrant packages.
  apt:
    name: "{{ devlaps_vagrant.deb_packages }}"
    update_cache: yes
