---
# defaults file for devlaps.common.
devlaps_common:
  redhat_packages:
    - curl
    - htop
    - iotop
    - lsof
    - ltrace
    - mc
    - net-tools
    - strace
    - tcpdump
    - telnet
    - vim
    - wget
    - ntp
    - traceroute
    - e4fsprogs
    - python-pip
    - kernel-devel # linux-headers-4.15.0-36-generic
    - "@Development tools" # build-essential
    - dkms
    - unzip
  deb_packages:
    - python-pip
    - linux-headers-4.15.0-36-generic
    - build-essential
    - dkms
    - unzip
  docker_pip_package: docker
