---
- hosts: all
  remote_user: vagrant
  sudo: yes
  environment:
    PATH: /home/vagrant/.pyenv/bin:{{ ansible_env.PATH }}
  vars:
    debug: False
  roles:
    - role: common
    - role: ahuffman.resolv
      resolv_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      resolv_domain: shipkode.com
      resolv_options:
        - timeout; 2
        - rotate
    - role: geerlingguy.docker
      docker_users:
        - vagrant
        # If you are using a bare metal server, add the ansible user name
        # here. This use must have sudo privileges.
        # - dlapsley
    - role: freedomofpress.docker-registry
    - role: devlaps.vagrant
      vbox_user: dlapsley
